# cd to this directory and `docker compose up -d`
name: tmp-apache-php
services:
  apache:
    image: httpd:latest
    container_name: httpd
    ports: # file-server w browse that does NOT parse php
    - '3001:80'
    volumes:
    - ${PWD}/hub:/usr/local/apache2/htdocs
  php:
    image: adminer
    container_name: php
    restart: always
    ports:
      - 1003:8080
    volumes:
      - ${PWD}/hub:/var/www/html/
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: dq_discussion_hub
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.5
    container_name: TEMP-db-relational
    environment:
      MYSQL_ROOT_USER: root 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dq_discussion_hub
      MYSQL_TCP_PORT: 3313
    ports:
      - 3313:3313
    volumes:
      - TEMP-db-relational:/var/lib/mysql
volumes:
  TEMP-db-relational: